# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.CharField(max_length=100000, null=True)),
                ('alt_mac_address', models.CharField(max_length=20, null=True)),
                ('asset_tag', models.CharField(max_length=200, null=True)),
                ('barcode_1', models.CharField(max_length=200, null=True)),
                ('barcode_2', models.CharField(max_length=200, null=True)),
                ('distribution_point', models.CharField(max_length=400, null=True)),
                ('initial_entry_date_utc', models.DateField(null=True)),
                ('ip_address', models.CharField(max_length=15, null=True)),
                ('itunes_store_account_is_active', models.NullBooleanField()),
                ('jamf_version', models.CharField(max_length=200, null=True)),
                ('last_contact_time_utc', models.DateTimeField(null=True)),
                ('mac_address', models.CharField(max_length=200, null=True)),
                ('mdm_capable', models.NullBooleanField()),
                ('mdm_capable_users', models.TextField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('netboot_server', models.CharField(max_length=200, null=True)),
                ('platform', models.CharField(max_length=200, null=True)),
                ('remote_management', models.TextField(null=True)),
                ('report_date_utc', models.DateField(null=True)),
                ('serial_number', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
