# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
