# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0003_auto_20160601_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='operating_systems',
            new_name='os_version',
        ),
    ]
