# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0003_auto_20160525_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('path', models.CharField(max_length=800)),
                ('version', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='applications',
            field=models.ManyToManyField(to='jss.ComputerApplication'),
        ),
    ]
