# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0005_auto_20160529_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerapplication',
            name='version',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
