# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0006_auto_20160601_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='os_version',
        ),
    ]
