# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0007_auto_20160529_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='applications',
            field=models.ManyToManyField(max_length=200, related_name='computers', to='jss.ComputerApplication'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='jss.Site'),
        ),
    ]
