# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0007_remove_computer_os_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='os_version',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
