# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0009_auto_20160601_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='warranty_expires',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
