# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0010_auto_20160601_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='warranty_expires',
        ),
        migrations.AddField(
            model_name='computer',
            name='warranty_expires_utc',
            field=models.DateField(null=True),
        ),
    ]
