# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0015_remove_computer_warranty_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='warranty_expires',
            field=models.DateField(null=True),
        ),
    ]
