# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0017_auto_20160601_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='total_ram',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
