# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0018_auto_20160601_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='real_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
