# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0019_auto_20160601_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='total_ram',
            new_name='total_ram_mb',
        ),
    ]
