# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-16 04:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jss', '0020_auto_20160603_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='extension_attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='computer',
            name='storage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
